"""
PDF Export

Converts Incident Reports to PDF, HTML, and Markdown formats.
"""

from typing import Optional
from pathlib import Path

from bloodflow_ai.reports.incident_report import IncidentReport


class ReportExporter:
    """
    Export reports to various formats.
    
    Supported formats:
    - Markdown (always available)
    - HTML (always available)
    - PDF (requires weasyprint or reportlab)
    """
    
    @staticmethod
    def to_markdown(report: IncidentReport, file_path: Optional[Path] = None) -> str:
        """
        Export report to Markdown.
        
        Args:
            report: IncidentReport to export
            file_path: Optional file path to write to
            
        Returns:
            Markdown string
        """
        markdown = report.to_markdown()
        
        if file_path:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(markdown)
        
        return markdown
    
    @staticmethod
    def to_html(report: IncidentReport, file_path: Optional[Path] = None) -> str:
        """
        Export report to HTML.
        
        Args:
            report: IncidentReport to export
            file_path: Optional file path to write to
            
        Returns:
            HTML string
        """
        # Convert markdown to HTML (using simple string replacement)
        markdown = report.to_markdown()
        
        # Simple markdown to HTML conversion
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BloodFlow AI — Incident Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
            color: #1a1a2e;
            background: #f5f7fa;
        }}
        .report {{
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }}
        h2 {{ color: #1a1a2e; margin-top: 30px; border-bottom: 1px solid #e0e0e0; padding-bottom: 8px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #e0e0e0; }}
        th {{ background: #f0f4f8; font-weight: 600; }}
        .status-success {{ color: #00aa66; font-weight: bold; }}
        .status-failed {{ color: #cc0033; font-weight: bold; }}
        .badge {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: 500;
        }}
        .badge-success {{ background: #e6f7ed; color: #00aa66; }}
        .badge-failed {{ background: #fde8e8; color: #cc0033; }}
        hr {{ border: none; border-top: 2px solid #e0e0e0; margin: 30px 0; }}
        .footer {{ margin-top: 40px; font-size: 0.85em; color: #888; text-align: center; }}
    </style>
</head>
<body>
    <div class="report">
        {ReportExporter._markdown_to_html(markdown)}
        <div class="footer">
            Generated by BloodFlow AI • {report.generated_at}
        </div>
    </div>
</body>
</html>
"""
        
        if file_path:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(html)
        
        return html
    
    @staticmethod
    def to_pdf(report: IncidentReport, file_path: Path) -> bool:
        """
        Export report to PDF using weasyprint.
        
        Args:
            report: IncidentReport to export
            file_path: File path to write to
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # pyrefly: ignore [missing-import]
            from weasyprint import HTML
            html_content = ReportExporter.to_html(report)
            HTML(string=html_content).write_pdf(file_path)
            print(f"[PDF Export] ✅ PDF saved to: {file_path}")
            return True
        except ImportError:
            print("[PDF Export] ⚠️ weasyprint not installed. Run: pip install weasyprint")
            
            # Fallback: save HTML instead
            html_path = file_path.with_suffix(".html")
            ReportExporter.to_html(report, html_path)
            print(f"[PDF Export] 💡 HTML saved to: {html_path}")
            return False
        except Exception as e:
            print(f"[PDF Export] ❌ Error: {e}")
            return False
    
    @staticmethod
    def _markdown_to_html(markdown: str) -> str:
        """
        Convert markdown to HTML (simple implementation).
        
        For production, use a proper markdown library like markdown or mistune.
        """
        lines = []
        in_table = False
        table_rows = []
        table_headers = []
        is_header_row = False
        
        for line in markdown.split('\n'):
            # Headers
            if line.startswith('# '):
                lines.append(f'<h1>{line[2:]}</h1>')
            elif line.startswith('## '):
                lines.append(f'<h2>{line[3:]}</h2>')
            elif line.startswith('### '):
                lines.append(f'<h3>{line[4:]}</h3>')
            # Horizontal rule
            elif line == '---':
                lines.append('<hr>')
            # Bold
            elif '**' in line:
                line = line.replace('**', '<strong>', 1)
                if '**' in line:
                    line = line.replace('**', '</strong>', 1)
                    line = line.replace('**', '<strong>')
                    line = line.replace('**', '</strong>')
                lines.append(f'<p>{line}</p>')
            # Table
            elif '|' in line and ':' in line and '---' in line:
                # Table header separator
                continue
            elif line.startswith('|') and line.endswith('|'):
                cells = [c.strip() for c in line[1:-1].split('|')]
                if not in_table:
                    in_table = True
                    table_headers = cells
                    is_header_row = True
                else:
                    if is_header_row:
                        table_rows.append(cells)
                        is_header_row = False
                    else:
                        table_rows.append(cells)
            elif in_table:
                # End of table
                html_table = '<table>\n'
                if table_headers:
                    html_table += '<thead><tr>' + ''.join(f'<th>{h}</th>' for h in table_headers) + '</tr></thead>\n'
                html_table += '<tbody>\n'
                for row in table_rows:
                    html_table += '<tr>' + ''.join(f'<td>{c}</td>' for c in row) + '</tr>\n'
                html_table += '</tbody>\n</table>'
                lines.append(html_table)
                in_table = False
                table_rows = []
                table_headers = []
                is_header_row = False
            # Empty line
            elif not line:
                continue
            # Regular paragraph
            else:
                lines.append(f'<p>{line}</p>')
        
        # Handle case where table is at the end
        if in_table and table_rows:
            html_table = '<table>\n'
            if table_headers:
                html_table += '<thead><tr>' + ''.join(f'<th>{h}</th>' for h in table_headers) + '</tr></thead>\n'
            html_table += '<tbody>\n'
            for row in table_rows:
                html_table += '<tr>' + ''.join(f'<td>{c}</td>' for c in row) + '</tr>\n'
            html_table += '</tbody>\n</table>'
            lines.append(html_table)
        
        return '\n'.join(lines)


class PDFExporter:
    """
    Wrapper for ReportExporter with simplified API.
    """
    
    @staticmethod
    def export(report: IncidentReport, file_path: Path, format: str = "markdown") -> bool:
        """
        Export a report to the specified format.
        
        Args:
            report: IncidentReport to export
            file_path: File path to write to
            format: "markdown", "html", or "pdf"
            
        Returns:
            True if successful, False otherwise
        """
        format = format.lower()
        
        if format == "markdown" or format == "md":
            ReportExporter.to_markdown(report, file_path)
            return True
        
        elif format == "html":
            ReportExporter.to_html(report, file_path)
            return True
        
        elif format == "pdf":
            return ReportExporter.to_pdf(report, file_path)
        
        else:
            print(f"[PDF Export] ❌ Unknown format: {format}")
            return False